version: "3"

services:
  vt-digital-assessment-frontend:
    build: ./client
    platform: linux/amd64
    image: vt-digital-assessment-client-frontend-img
    container_name: client-frontend
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "5001:5001"
    depends_on:
      - vt-digital-assessment-backend
    networks:
      - vt_digital_assessment_network
  
  vt-digital-assessment-backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE="production"
    platform: linux/amd64
    image: vt-digital-assessment-server-backend-img
    container_name: server-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - vt_digital_assessment_network
  
networks:
  vt_digital_assessment_network:
    name: shared_network
    driver: bridge
